dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "eD03wWDAJTlXRq7vVupnBCheynGv6iMrCGqdtVRiFZtvH7UuSaYXn2s2BwNfPFVvVXSHovtwkXyWNYDmgMyOveWdLJTb177KrwyHX8p0BBf151np4FU9shaV/ekV1ZY/nB+9YRAhIL6dN9vmbim/vqsP5HRmR5UxjvH5CBFL3Sokox/jKHah3MDxaVPbvnvF+IrtfSUsfiAbjeac7oNexaZF5vgSR9F4/iEiKK1NPQjfvAQw+6uKFKIhUkkSX0TTBDIMsfmcfiiloTX1OLZ1TBq2LWA96+nOiIzzLBddYhbLmFjhOeUmmd1BMfj0NuQYBalZcV4AiLZ3ptiCKtfj2YuOZCUKcw7xFFcvk41ccL0+iLn8JysOZZhSPIIu3IXycrVMa8ujH3Z9JSB+O3u7PyEMXci9KZ3eylVZ06iR98BLMrxba6sy2HGwDi/a8eHWEx3xQiKOe1dCsfQ7WqfJA4qYqkcuDrMdGeGzp3mPa4wc9E8JyLALI+JJNep7r5LFRcFVNFHT6tz69uTjkxMZ3ObK4Ol8wbpRNAmnk/r54y4jkfQ4KaYxaJ58uhcWhWDCcGSIhhUdeWKsfPwULWsF0MUKJeq6bm6qwUrubwRJ/0N1xeqNcEQXTLndt11iDGsIajJyj0gdsoVviWctIwXpfWItXNe7Z+qfofwLHKeQkCY="
    - secure: "FTTaYDAgWMFZhCBFL5PccYNTa2gcmfxhiHPZh09rm+Wcbdc+AR30FzkM4rYHHOSPTNH/Sog1NqbRHlOZK4Kw1etm1Gxnut9N3DrPi5rVWhaCdvHsPwklAYzvNTvrOD7TM9k0Al6dtLowKNklTrkshj8OUjORs+8lmrj02DRSAfXMEEVvU/lEfCwzfYnYf2M1xq6Euy4y6BY+tvdvZcn5PzSq/0RQFMimwf1ECvo4EXclJ4nLAt07nUxaL7TtDPmKlFNFeeygaNy9xNWy6kN33v6N1xZpqIgpCO08Ib69/0MyU7MaL/UZtHnx+vqzuowU5m8XlDyCop7+ZzhpQCfy9via/RksRNX9mzAwt4JS/clS2K4CMrGxpL9Ei1HCes2blO/IlP7eqn2bUAU4aF/7TwwS4y+zAxIZLHQm5tQYqGwc8HuOgvyuJqA0LnKHkIKOEwGxaxylQJkZ09LQQpiGMSgviQFG+4VaRe2QuRMcvac70zNvizx5bYRNsJ5RMYNZCvTWsyx8os/5Si1zb352niWlG1neME/AGxW6gz5dd9SSCCJ98OEK+PPAlOGip/IWTKoQnySfcJNOE12r1g08q9kYjXznngeaAwlAOrBDBrneOW4zOc+CdTCs61VtcmpTTZsYivpDT2sfxhCGmXcllCY7WdPVPg6vBE88ZMGz+wA="
    - secure: "j+wVtBH5tmVlRC1YXM/yc5MshecqDW+7Yz5Cs5+6Ol3b5OVJ43FRYChEcrTKbkGSaPirluXLHQ5E+yPLnE3v3c4WQFZjiqjH8I6+GzpqNU6edttzALCO14uFBCpqE1M7W4Vz9Ijpt9vzqJ8YE3wNMUucOoVwoDfg+oZO0/RI/lgqvn9VwswGShOGq8M440NPfRhybN+BCz2TqLqyeWQ1+wo0/P3SS7bE0HePmv3s6iAqfNQZI8NKwWTcWxps9YLev9r8ihoRMxqWQ7u33HqlIRd80APmgFTr7C3+7DSHqOMgIaxSca1r4y4T7XAujdCbMrIwnXku1gglzYhGn4GgS46+XJjlmDXFe8Ffm5BQpd2/rcfRvmpVTbUTNUJQ8KsH4uFsBCO7o+BxfIvTWUWxvbpl8EpzR2U1ErPb3TBOsMZQnR8dcpeRPdK2oQA3FpvHfCkLuts/AhdbwwFLA24YCS5df9lqGHViSn/ybNjn+qkjn3BI9AYahYE2eMM7ve2aiIkpos454E02ntN+dXPlKmzuPxMO7mYfSON8RDVfcp55p+Q4ispNrDodGZxr2KyDAoU8uhG5KqOr0zXffuVkReTztWLvUoo2jH66qQaipcIpEQ33AwVmApf2LlsThWwVKR9wtUqQNcDhBtnPYykDEgjy8gSsMAi6lSR4x7383ZQ="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=sheffer/simplerepo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: ratnikovsimpleapi