dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "OkuNGTBTQWNgXAXM1qGh/JADjDkWqbZMBbvjtPgIbQbNUGbSdmYCjBym4W0lykdSzkjltVF7YG737uHYcIe6XJ13IgNGrlJNqOvLbS+fICH8lS+65qhiC8tzW6703q9dF9hAUP4E6tC7F+dghEOct7Dz1lhyYzye5zAMDz05GpB8JkgYkLn8+SuEt3/Pd2g6Xw+RsI1J4ysq3dwLxnCE0CJ2zCmaXwyaWomTSdBx1uQSDhmHWTdRRDJ31qD5+VaZrO3/rBLCNjMKyUZkKeGvjTnYtBgrT3kGMfxGXL2MipA1/wqTeQpqflJCxK7HigbeQgnxvhDixl+U6Og5WEf4zj9T2S9NBY8x6QCihWT4yQ54jAeXkZVC+4pjaHjbFndgIw05Gquz2yBbSJCu5lpWs+/E6kTbp8AuM+x25sbuciss+/y5rHSstQYCmg28tGC/N+LqVgmQdx5PpuEYPAodY/c5wY/9aRXdzG7IMa5ALG9Q50heSX87sRqfuAMOW5Thug+i3RjUJFTEtnxMSTC4cbaryFaLQ3Ox9FsCMOWCexUHZgkNiX8EUzlY22s9A7VdqXhq7aBqRnNMo+o7WlAaF5SKqvvDZV3M1goC4tkhEqyaJgyIpyzgz1d99wywD4IfkZVHTwXbOZtw8VZosymyAu2oy663onM18l79RYa/OgE="
    - secure: "Qo2jCB0590v70DEYyc3mf1fY1QGOF627dp32NawQooF5YS9Amrzgw6Xpq/CxIYstNSTuxsTPxbak4/U0RIqMjgCNi5ww4MRd4grSjXnlevonqqxkA31HKcbtXPjICHvlwu++0sJtYvisZVMymuhVwuuZW5fkJDYpF8r8vN4VcpKHc2KsWvFb9l3GmFSM3TUzbGfsydMzghPthPGSbQqctAR9EcfvsyCAIR1uC5fOQs9hnqUGpJBFLnO/hLMlz0JZZBeNfQj2uT7beOFLKL3BSacNJkEkeEH4e80ooUobxlzQUex5c/4J1Zxxd3M2HkxfvhmgeFPEhUk7gzY2KxOGtKGp9Dh2sAlPOwDCxKv5hUpdZUmG+J5Kqn+61TiB4Y/TbvF9N/NSCs08+9kA4D6x7uF/8y6etys3nfkHaEbjwEFGA/PjqDQa4hu0gi127NY8nQG8mDThqkxR34Q7paqNqDMCFCIstmYSsnSrKxU9bwCBMurv5nelGRl4IjUatqrZKtPvVwRZZ737IfnDkL1OZvWZZyu5p0WkWg0iNFqPSE7w/ON8cMzuD3sT5whzAgkxaf+WnI/nzhoD6QWlRTuYtkzgJODtiA064n1fu8MoSWf+hnfTrq5YVPERCNe7jS7Q3EYcHEwLvRZDajg9XFXMtXpCI5G332KvCJ5NIUVZVfI="
    - secure: "FTTaYDAgWMFZhCBFL5PccYNTa2gcmfxhiHPZh09rm+Wcbdc+AR30FzkM4rYHHOSPTNH/Sog1NqbRHlOZK4Kw1etm1Gxnut9N3DrPi5rVWhaCdvHsPwklAYzvNTvrOD7TM9k0Al6dtLowKNklTrkshj8OUjORs+8lmrj02DRSAfXMEEVvU/lEfCwzfYnYf2M1xq6Euy4y6BY+tvdvZcn5PzSq/0RQFMimwf1ECvo4EXclJ4nLAt07nUxaL7TtDPmKlFNFeeygaNy9xNWy6kN33v6N1xZpqIgpCO08Ib69/0MyU7MaL/UZtHnx+vqzuowU5m8XlDyCop7+ZzhpQCfy9via/RksRNX9mzAwt4JS/clS2K4CMrGxpL9Ei1HCes2blO/IlP7eqn2bUAU4aF/7TwwS4y+zAxIZLHQm5tQYqGwc8HuOgvyuJqA0LnKHkIKOEwGxaxylQJkZ09LQQpiGMSgviQFG+4VaRe2QuRMcvac70zNvizx5bYRNsJ5RMYNZCvTWsyx8os/5Si1zb352niWlG1neME/AGxW6gz5dd9SSCCJ98OEK+PPAlOGip/IWTKoQnySfcJNOE12r1g08q9kYjXznngeaAwlAOrBDBrneOW4zOc+CdTCs61VtcmpTTZsYivpDT2sfxhCGmXcllCY7WdPVPg6vBE88ZMGz+wA="
    - secure: "j+wVtBH5tmVlRC1YXM/yc5MshecqDW+7Yz5Cs5+6Ol3b5OVJ43FRYChEcrTKbkGSaPirluXLHQ5E+yPLnE3v3c4WQFZjiqjH8I6+GzpqNU6edttzALCO14uFBCpqE1M7W4Vz9Ijpt9vzqJ8YE3wNMUucOoVwoDfg+oZO0/RI/lgqvn9VwswGShOGq8M440NPfRhybN+BCz2TqLqyeWQ1+wo0/P3SS7bE0HePmv3s6iAqfNQZI8NKwWTcWxps9YLev9r8ihoRMxqWQ7u33HqlIRd80APmgFTr7C3+7DSHqOMgIaxSca1r4y4T7XAujdCbMrIwnXku1gglzYhGn4GgS46+XJjlmDXFe8Ffm5BQpd2/rcfRvmpVTbUTNUJQ8KsH4uFsBCO7o+BxfIvTWUWxvbpl8EpzR2U1ErPb3TBOsMZQnR8dcpeRPdK2oQA3FpvHfCkLuts/AhdbwwFLA24YCS5df9lqGHViSn/ybNjn+qkjn3BI9AYahYE2eMM7ve2aiIkpos454E02ntN+dXPlKmzuPxMO7mYfSON8RDVfcp55p+Q4ispNrDodGZxr2KyDAoU8uhG5KqOr0zXffuVkReTztWLvUoo2jH66qQaipcIpEQ33AwVmApf2LlsThWwVKR9wtUqQNcDhBtnPYykDEgjy8gSsMAi6lSR4x7383ZQ="
    - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "illigt"
    token: ${SONAR_TOKEN}

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=IllIgt_simpleapi


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=sheffer/simplerepo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: ratnikovsimpleapi